[package]
name = "clappy-e2e"
version = "1.0.0"
edition = "2024"

[dependencies]
cucumber = "0.21"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
async-trait = "0.1"
clappy-cli = { path = "../clappy-cli" }
anyhow = "1"
tempfile = "3"
llm-client = { path = "../llm-client" }
