[package]
name = "plugin-sdk"
version = "1.0.0"
edition = "2024"
authors = ["CLAppy Contributors"]

[dependencies]
anyhow = "1"
wasmtime = "19"
tokio = { version = "1", features = ["rt"] }
llm-client = { path = "../llm-client" }

[dev-dependencies]
rstest = "0.18"
wiremock = "0.6"
